oj/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
import os

urlpatterns = [
    url(r'^$', 'oj_core.views.index', name='index'),
    url(r'^problem/(?P<problem_id>[^/]+)/$', 'oj_core.views.show_problem', name='problem'),
    url(r'^submit/(?P<problem_id>[^/]+)/$', 'oj_core.views.submit', name='submit'),
    url(r'^problemstatus/(?P<problem_id>[^/]+)/$', 'oj_core.views.problemstatus', name='problemstatus'),
    url(r'^problemset/', 'oj_core.views.problem_set', name='problemset'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name='login'), 
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'logout.html'}, name='logout'), 
    url(r'^register/$', 'oj_core.views.registerpage', name='registerpage'),
    url(r'^userinfo/(?P<user_id>[^/]+)/$', 'oj_core.views.userinfo', name='userinfo'),
    url(r'^status/', 'oj_core.views.status', name='status'),
    url(r'^ranklist/', 'oj_core.views.ranklist', name='ranklist'),
]+static('/static/', document_root=os.path.join(settings.BASE_DIR,'static'))

oj_core/models.py
from django.db import models
from .proglang import proglang
from django.contrib.auth.models import User

# Create your models here.
class Problem(models.Model):
    name = models.CharField(max_length=100)
    background = models.TextField(blank=True)
    description = models.TextField(blank=True)
    input = models.TextField(blank=True)
    output = models.TextField(blank=True)
    sample_input = models.TextField(blank=True)
    sample_output = models.TextField(blank=True)
    time_limitation = models.TextField(blank=True)
    hint = models.TextField(blank=True)
    source = models.TextField(blank=True)
    submit=models.PositiveIntegerField(default=0)
    ac=models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.name
    __repr__ = __str__
    class Meta:
        ordering = ['name']
        unique_together = ("name", "description")

class Data(models.Model):
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    data_hash = models.CharField(max_length=32)
    def __str__(self):
        try:
            return self.problem.name+" ("+self.data_hash+")"
        except Exception as e:
            return "* ("+self.data_hash+")"
    __repr__ = __str__
    class Meta:
        verbose_name = 'datum'
        verbose_name_plural = 'data'
        ordering = ['problem']
        
class UserStatus(models.Model):
    user_id = models.PositiveIntegerField(primary_key=True)
    submit=models.PositiveIntegerField(default=0)
    ac=models.PositiveIntegerField(default=0)
    submit_problems=models.PositiveIntegerField(default=0)
    ac_problems=models.PositiveIntegerField(default=0)
    solved_problems=models.ManyToManyField(Problem, related_name='solved_by')
    tried_problems=models.ManyToManyField(Problem, related_name='tried_by')
    def get_name(self):
        try:
            return User.objects.get(pk=self.user_id).username
        except Exception as e:
            return "Non-exist user"
    def get_nickname(self):
        try:
            return User.objects.get(pk=self.user_id).first_name
        except Exception as e:
            return ""
    def __str__(self):
        return self.get_name()+" ("+str(self.user_id)+")"
    __repr__ = __str__
    class Meta:
        verbose_name_plural = 'user statuses'
        ordering = ['user_id']
    
class Status(models.Model):
    runid=models.UUIDField()
    user=models.ForeignKey(UserStatus, on_delete=models.SET_NULL, null=True)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    score=models.PositiveSmallIntegerField(default=0)
    result=models.PositiveSmallIntegerField(default=10)
    memory=models.PositiveIntegerField(default=0)
    time=models.FloatField(default=0)
    language=models.CharField(max_length=7, choices=proglang)
    code=models.TextField()
    code_length=models.PositiveIntegerField()
    submit_time=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.pk)+" - "+str(self.runid)+" ("+str(self.user or "Anonymous")+" / "+str(self.problem)+")"
    __repr__ = __str__
    class Meta:
        verbose_name_plural = 'statuses'
        ordering = ['-submit_time']

oj_core/forms.py
from django import forms
from .proglang import proglang
from .result_name import *
allresult=(("","All"),)

class RegisterPage(forms.Form):
    user_id = forms.CharField(label='User ID', max_length=100)
    password = forms.CharField(label='Password', max_length=100,widget=forms.PasswordInput())
    rptpassword = forms.CharField(label='Repeat Password', max_length=100,widget=forms.PasswordInput())
    nick_name = forms.CharField(label='Nick Name', max_length=100,required=False)
    
class SubmitPage(forms.Form):
    language = forms.ChoiceField(label='Language', choices=proglang)
    source = forms.CharField(label='Source code',widget=forms.Textarea())
    
class StatusSearch(forms.Form):
    problem_id = forms.IntegerField(label='Problem ID',required=False)
    user_id = forms.CharField(label='User ID',required=False)
    language = forms.ChoiceField(label='Language', choices=allresult+proglang,required=False)
    result = forms.ChoiceField(label='Result', choices=allresult+result_tuple,required=False)
    

oj_core/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import *
from .forms import *
from datetime import datetime, timedelta, timezone
from django.conf import settings
import json, os, socket, uuid, threading
from .result_name import *
# Create your views here.
def_limit=100
timestamp=0
def index(request):
    return render(request, 'base.html', {})
def show_problem(request, problem_id):
    problem = Problem.objects.get(pk=problem_id)
    return render(request, 'problem.html', {'problem_id':problem_id,'problem':problem})
def problemstatus(request, problem_id):
    problem = Problem.objects.get(pk=problem_id)
    return render(request, 'problemstatus.html', {'id':problem_id,'submit':problem.submit,'ac':problem.ac,'solved':problem.solved_by.get_queryset().count(),'tried':problem.tried_by.get_queryset().count()})
def problem_set(request):
    offset = int(request.GET.get('offset','0'))
    limit = int(request.GET.get('limit',def_limit))
    all_problemset = Problem.objects.all()
    problemset = all_problemset[offset:offset+limit]
    pages=[(n,def_limit*n-def_limit) for n in range(1,(all_problemset.count()-1)//def_limit+2)]
    return render(request, 'problemset.html', {'problemset':problemset,'pages':pages,'curpage':offset//limit+1 if ((limit==def_limit) and (offset%limit==0)) else 0})
def registerpage(request):
    error=''
    if request.method == 'POST':
        form = RegisterPage(request.POST) 
        if form.is_valid():
            if form.cleaned_data['password']==form.cleaned_data['rptpassword']:
                user = User()
                user.username = form.cleaned_data['user_id']
                user.set_password(form.cleaned_data['password'])
                user.first_name=form.cleaned_data['nick_name']
                try:
                    user.save()
                except Exception as e:
                    error='User Existed!'
            else:
                error='Password Not Same!'
        else:
            error='Invalid Data!'
        if error=='':
            return render(request, 'base.html', {})
    else:
        form = RegisterPage()
    return render(request, 'registerpage.html', {'form': form, 'error': error})
def submit_async(problem_id,language,source,userid):
    data=Problem.objects.get(pk=problem_id).data_set.get_queryset()[0].data_hash
    data_send=json.dumps([1,[{"input":'',"output":'',"judgemode":7},[language,source],data]])
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect(('127.0.0.1', 28522))
    s.send(data_send.encode('utf-8'))
    judge_result=json.loads(s.recv(1048576).decode('utf-8'))
    if judge_result[0]==1:
        with open(os.path.join(settings.BASE_DIR,'data',data+'.json'), 'r') as f:
            realdata=f.read()
        s.send(realdata.encode('utf-8'))
        judge_result=json.loads(s.recv(1048576).decode('utf-8'))
        while judge_result[0]==4:
            if judge_result[1]==10:
                print("error!")
            s.send(b'')
            judge_result=json.loads(s.recv(1048576).decode('utf-8'))
    record_hash=judge_result[1]
    s.close()
    new_result=Status()
    new_result.runid=uuid.UUID(record_hash)
    new_result.language=language
    new_result.code=source
    new_result.code_length=len(source)
    new_result.problem=Problem.objects.get(pk=problem_id)
    if userid!=0:
        new_result.user=UserStatus.objects.get_or_create(pk=userid)[0]
    new_result.save()
def submit(request, problem_id):
    if request.method == 'POST':
        form = SubmitPage(request.POST) 
        if form.is_valid():
            threading.Thread(target=submit_async,args=(problem_id,form.cleaned_data['language'],form.cleaned_data['source'],request.user.id if request.user.is_authenticated() else 0)).start()
            form = "Done"
    else:
        form = SubmitPage()
    return render(request, 'submitpage.html', {'form': form})
def status(request):
    global timestamp
    if datetime.now().timestamp()-timestamp>10:
        for i in Status.objects.all().filter(result=jresult.R.value):
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.connect(('127.0.0.1', 28522))
            s.send(json.dumps([2,str(i.runid)]).encode('utf-8'))
            judge_result=json.loads(s.recv(1048576).decode('utf-8'))
            s.close()
            if judge_result[0]==0:
                judge_result=judge_result[1]
                i.score=judge_result[1]
                final_result=jresult.AC.value
                final_time=0
                for j in judge_result[0]:
                    if j[0]!=jresult.AC.value:
                        final_result=j[0]
                    final_time=max(final_time,j[1])
                i.result=final_result
                i.time=final_time
                i.save()
                i.problem.submit=i.problem.submit+1
                if final_result==jresult.AC.value:
                    i.problem.ac=i.problem.ac+1
                i.problem.save()
                if i.user:
                    if final_result==jresult.AC.value:
                        i.user.ac=i.user.ac+1
                        if not i.user.solved_problems.get_queryset().filter(pk=i.problem.pk).exists():
                            i.user.solved_problems.add(i.problem)
                            i.user.ac_problems=i.user.ac_problems+1
                    if not i.user.tried_problems.get_queryset().filter(pk=i.problem.pk).exists():
                        i.user.tried_problems.add(i.problem)
                        i.user.submit_problems=i.user.submit_problems+1
                    i.user.submit=i.user.submit+1
                    i.user.save()
    offset = int(request.GET.get('offset','0'))
    limit = int(request.GET.get('limit',def_limit))
    form = StatusSearch(request.GET)
    status_query=Status.objects.all()
    param=''
    if form.is_valid():
        if form.cleaned_data['problem_id'] or ''!='':
            status_query=status_query.filter(problem_id=form.cleaned_data['problem_id'])
            param+='&problem_id='+form.cleaned_data['problem_id']
        if form.cleaned_data['user_id'] or ''!='':
            try:
                status_query=status_query.filter(user_id=User.objects.get(username=form.cleaned_data['user_id']).id)
            except Exception as e:
                status_query=Status.objects.none()
            param+='&user_id='+form.cleaned_data['user_id']
        if form.cleaned_data['language'] or ''!='':
            status_query=status_query.filter(language=form.cleaned_data['language'])
            param+='&language='+form.cleaned_data['language']
        if form.cleaned_data['result'] or ''!='':
            status_query=status_query.filter(result=form.cleaned_data['result'])
            param+='&result='+form.cleaned_data['result']
    status_iter = status_query[offset:offset+limit]
    status_list=[{'id':x.pk,'userid':x.user.pk if x.user else 0,'username':x.user.get_name() if x.user else 'Anonymous','problem':x.problem.pk,'result':result_name[jresult(x.result)],'memory':x.memory,'memory':x.memory,'time':'%.0f' % (x.time*1000),'language':x.get_language_display(),'code_length':x.code_length,'submit_time':x.submit_time.astimezone(timezone(timedelta(hours=8))).strftime('%Y-%m-%d %H:%M:%S')} for x in status_iter]
    return render(request, 'status.html', {'form':form,'status_list':status_list,'limit':limit,'prev_offset':max(offset-limit,0),'next_offset':offset+limit,'param':param})
def userinfo(request, user_id):
    user=UserStatus.objects.get(pk=int(user_id))
    solved_problems=[x.pk for x in user.solved_problems.get_queryset()]
    tried_problems=list({x.pk for x in user.tried_problems.get_queryset()}-set(solved_problems))
    return render(request, 'userinfo.html', {'user_id':user_id,'username':user.get_name(),'nickname':user.get_nickname(),'ac':user.ac,'submit':user.submit,'ac_problems':user.ac_problems,'submit_problems':user.submit_problems,'solved_problems':solved_problems,'tried_problems':tried_problems})
def ranklist(request):
    offset = int(request.GET.get('offset','0'))
    limit = int(request.GET.get('limit',def_limit))
    ranklist_all=UserStatus.objects.all().order_by('-ac','submit')
    ranklist_iter=ranklist_all[offset:offset+limit]
    ranklist_list=[{'ranking':i+offset,'userid':x.pk,'username':x.get_name(),'nickname':x.get_nickname(),'ac':x.ac_problems,'submit':x.submit_problems,'ratio':'%.3f%%'%((100*x.ac/x.submit) if x.submit else 0)} for i, x in enumerate(ranklist_iter)]
    pages=[(n*def_limit-def_limit,n*def_limit-def_limit+1,n*def_limit) for n in range(1,(ranklist_all.count()-1)//def_limit+2)]
    return render(request, 'ranklist.html', {'ranklist':ranklist_list,'pages':pages})
    

oj_core/templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}Starter Template for Bootstrap{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    {% block header %}{% endblock header %}
  </head>

  <body style="padding-top: 50px">

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">OJ</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'problemset' %}">ProblemSet</a></li>
            <li><a href="{% url 'status' %}">Status</a></li>
            <li><a href="{% url 'ranklist' %}">Ranklist</a></li>
            <li><a href="{% url 'login' %}">Login</a></li>
            <li><a href="{% url 'registerpage' %}">Register</a></li>
          </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a href="#"">{{ user.username }}</a></li>
            </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container" style="padding: 40px 15px;">
{% block content %}
{% endblock content %}
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/static/jquery-1.11.3.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    {% block footer %}{% endblock footer %}
  </body>
</html>

oj_core/templates/login.html
{% extends "base.html" %}
 
{% block title %}
LOGIN
{% endblock title %}

{% block content %}
    {% if form.errors %}  
        <p>Your username and password didn't match. Please try again.</p>  
    {% endif %}  
    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">  
    {% csrf_token %}  
            <table>  
            <tr>  
                <td>{{ form.username.label_tag }}</td>  
                <td>{{ form.username }}</td>  
            </tr>  
            <tr>  
                <td>{{ form.password.label_tag }}</td>  
                <td>{{ form.password }}</td>  
            </tr>  
            </table>  
  
        <input type="submit" value="login" />  
        <input type="hidden" name="next" value="{{ next }}" />  
    </form>  
{% endblock content %}

oj_core/templates/logout.html
{% extends "base.html" %}
 
{% block title %}
LOGOUT
{% endblock title %}

{% block content %}
bye
{% endblock content %}

oj_core/templates/notice.html
<div><B>Notice:</B>由于本OJ建立在Linux平台 下，而许多试题数据是在Windows下制作，请注意输入输出语句的选择，及变量类型的选择等问题，避免无谓的RE出现。</div>

oj_core/templates/problem.html
{% extends "base.html" %}
 
{% block title %}
{{ problem_id }}: {{ problem.name }}
{% endblock title %}

{% block content %}
<h2>{{ problem_id }}: {{ problem.name }}</h2><span class=green>Time Limit: </span>{{ problem.time_limitation }}&nbsp;&nbsp;<span class=green>Memory Limit: </span>{{ problem.memory_limitation }}<br><span class=green>Submit: </span>{{ problem.submit }}&nbsp;&nbsp;<span class=green>Solved: </span>{{ problem.ac }}<br>[<a href='{% url 'submit' problem_id %}'>Submit</a>][<a href='{% url 'problemstatus' problem_id %}'>Status</a>][<a href='bbs.php?id=1000'>Discuss</a>]</center>{% autoescape off %}<h2>Description</h2><div class=content>{{ problem.description }}</div><h2>Input</h2><div class=content>{{ problem.input }}</div><h2>Output</h2><div class=content>{{ problem.output }}</div><h2>Sample Input</h2>
			<div class=content><span class=sampledata>{{ problem.sample_input }}</span></div><h2>Sample Output</h2>
			<div class=content><span class=sampledata>{{ problem.sample_output }}</span></div><h2>HINT</h2>
			<div class=content><pre>{{ problem.hint }}</pre></div><h2>Source</h2>
			<div class=content>{{ problem.source }}</div>{% endautoescape %}<center>[<a href='{% url 'submit' problem_id %}'>Submit</a>][<a href='{% url 'problemstatus' problem_id %}'>Status</a>][<a href='bbs.php?id=1000'>Discuss</a>]
{% endblock content %}

oj_core/templates/problemset.html
{% extends "base.html" %}
 
{% block title %}
Problem Set
{% endblock title %}

{% block content %}
<script src="/static/include/sortTable.js"></script>
<h3 align='center'>{% for i,ki in pages %}{% if i == curpage %}<span class=red>{{ i }}</span>{% else %}<a href='{% url 'problemset' %}?offset={{ ki }}'>{{ i }}</a>{% endif %}{% if not forloop.last %}&nbsp;{% endif %}{% endfor %}</h3><center><table id='problemset' width='90%'><thead><tr align='center'><td width='5'></td><td width='100%' colspan='6'><form>Search<input type='text' name='search'><input type='submit' value='GO' ></form></td></tr><tr><td width='100%' colspan='6'><center>说明：输入题号直接进入相应题目，如需搜索含数字的题目，请在关键词前加单引号</center></td></tr><tr align=center class='toprow'><td width='5'><td style="cursor:hand" onclick="sortTable('problemset', 1, 'int');" width=10%><A>Problem ID</A><td width='60%'>Title</td><td width='20%'>Source</td><td style="cursor:hand" onclick="sortTable('problemset', 4, 'int');" width='5%'><A>AC</A></td><td style="cursor:hand" onclick="sortTable('problemset', 5, 'int');" width='5%'><A>Submit</A></td></tr></thead><tbody>{% for i in problemset %}
<tr><td></td><td align='center'>{{ i.id }}</td><td align='left'><a href='{% url 'problem' i.id %}'>{{ i.name }}</a></td><td align='center'>{{ i.source }}</td><td align='center'><a href='status.php?problem_id=1000&jresult=4'>{{ i.ac }}</a></td><td align='center'><a href='status.php?problem_id=1000'>{{ i.submit }}</a></td></tr>
{% endfor %}</tbody></table>
{% endblock content %}

oj_core/templates/problemstatus.html
{% extends "base.html" %}
 
{% block title %}
Problem {{ id }} Status
{% endblock title %}

{% block content %}
Submit: {{ submit }}<br>
User(Submit): {{ tried }}<br>
User(Solved): {{ solved }}<br>
AC: {{ ac }}<br>
{% endblock content %}

oj_core/templates/ranklist.html
{% extends "base.html" %}
 
{% block title %}
Rank List
{% endblock title %}

{% block content %}
<table width=90%><tr><td colspan=3 align=left><form action=>
				User<input name=user>
				<input type=submit value=Go>
			</form></td><td colspan=3 align=right>
			<a href=ranklist.php?scope=d>Day</a>
			<a href=ranklist.php?scope=w>Week</a>
			<a href=ranklist.php?scope=m>Month</a>
			<a href=ranklist.php?scope=y>Year</a>
			</td></tr><tr class='toprow'>
				<td width=5% align=center><b>No.</b>
				<td width=10% align=center><b>User</b>
				<td width=55% align=center><b>Nick Name</b>
				<td width=10% align=center><b>AC</b>
				<td width=10% align=center><b>Submit</b>
				<td width=10% align=center><b>Ratio</b></tr>{% for i in ranklist %}<tr><td align=center>{{ ranklist.ranking }}<td align=center><a href='{% url 'userinfo' i.userid %}'>{{ i.username }}</a><td align=center>{{ i.nickname }}<td align=center><a href='{% url 'status' %}?user_id={{ i.userid }}&jresult=4'>{{ i.ac }}</a><td align=center><a href='{% url 'status' %}?user_id={{ i.userid }}'>{{ i.submit }}</a><td align=center>{{ i.ratio }}</tr>{% endfor %}</table></center><center>{% for i,si,ti in pages %}<a href='./ranklist.php?start={{ i }}'>{{ si }}-{{ ti }}</a>&nbsp;{% endfor %}<br></center>		
{% endblock content %}

oj_core/templates/registerpage.html
{% extends "base.html" %}
 
{% block title %}
Register Page
{% endblock title %}

{% block content %}
<big><strong>{{ error }}</strong></big>
<form method='post'>
{% csrf_token %}
<table>
{{ form }}
<tr><td><input type="submit" value="提交"></td></tr>
</table>
</form>
{% endblock content %}

oj_core/templates/status.html
{% extends "base.html" %}
 
{% block title %}
Submission Status
{% endblock title %}

{% block content %}
<form id=simform method="get">
<table>
{{ form }}
<tr><td>
<input type=submit value='Search'></td></tr>
</table>
</form>
<table align=center>
<tr  class='toprow'>
<td width="8%">RunID<td width="10%">User<td width="6%">Problem<td width="17%">Result<td width="10%">Memory<td width="8%">Time<td width="6%">Language<td width="10%">Code_Length<td width="17%">Submit_Time</tr>
{% for i in status_list %}<tr align=center><td>{{ i.id }}<td>{% if i.userid > 0 %}<a href='{% url 'userinfo' i.userid %}'>{{ i.username }}</a>{% else %}{{ i.username }}{% endif %}<td><a href='{% url 'problem' i.problem %}'>{{ i.problem }}</a><td>{{ i.result }}<td>{{ i.memory }} <font color=red>kb</font><td>{{ i.time }} <font color=red>ms</font><td>{{ i.language }}<td>{{ i.code_length }} B<td>{{ i.submit_time }}</tr>{% endfor %}</table>
[<a href={% url 'status' %}>Top</a>]&nbsp;&nbsp;[<a href={% url 'status' %}?offset={{ prev_offset }}&limit={{ limit }}{{ param }}>Previous Page</a>]&nbsp;&nbsp;[<a href={% url 'status' %}?offset={{ next_offset }}&limit={{ limit }}{{ param }}>Next Page</a>]</center>
{% endblock content %}

oj_core/templates/submitpage.html
{% extends "base.html" %}
 
{% block header %}
<script src="/static/codemirror/codemirror.js"></script>
<link rel="stylesheet" href="/static/codemirror/codemirror.css">
<script src="/static/codemirror/pascal.js"></script>
<script src="/static/codemirror/clike.js"></script>
{% endblock header %}

{% block title %}
Submit Code
{% endblock title %}

{% block content %}

<form method='post'>
{% csrf_token %}
<table>
{{ form }}
<tr><td><input type="submit" value="提交"></td></tr>
</table>
</form>
{% endblock content %}

{% block footer %}
<script>
function mine() {
    switch(language_select.val())
    {
    case "pas":
        return "text/x-pascal";
    case "c":
        return "text/x-csrc";
    case "cpp":
        return "text/x-c++src";
    };
}
function make_editor() {
    	window.editor = CodeMirror.fromTextArea(document.getElementById('id_source'), {
	    mode: mine(),
	    smartIndent: true,
	    lineNumbers: true,
	  });
    }
function switch_editor() {
    	window.editor.toTextArea()
        make_editor()
    }

var language_select = $('#id_language');
language_select.on('change', switch_editor);
$(document).on('ready', make_editor);
</script>
{% endblock footer %}

oj_core/templates/userinfo.html
{% extends "base.html" %}
 
{% block title %}
User--{{ username }}
{% endblock title %}

{% block content %}
User ID: {{ userid }}<br>
Username: {{ username }}<br>
Nickname: {{ nickname }}<br>
Tried: {{ submit_problems }}<br>
Solved: {{ ac_problems }}<br>
Submit: {{ submit }}<br>
AC: {{ ac }}<br>
Problems: {% for i in solved_problems %}<a href='{% url 'problem' i %}'>{{ i }}</a> {% endfor %}{% for i in tried_problems %}<s><a href='{% url 'problem' i %}'>{{ i }}</a></s> {% endfor %}
{% endblock content %}